@token = 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
@accepHeader = application/vnd.github.v3.html.json
//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
@baseUrl = https://api.github.com

### Starred Repo

GET {{baseUrl}}/user/starred
    ?page=1 
Authorization : bearer {{token}}
Accept: {{accepHeader}}

### Search Repo

GET {{baseUrl}}/search/repositories
    ?q=flutter
    &page=1
Authorization : bearer {{token}}
Accept: {{accepHeader}}

### Get Readme

GET {{baseUrl}}/repos/flutter/flutter/readme
Accept: {{accepHeader}}
Authorization : bearer {{token}}

### Star a Repo

PUT {{baseUrl}}/user/starred/titisriz/notesapp
Accept: {{accepHeader}}
Authorization : bearer {{token}}
Content-Length: 0

### Unstar a Repo

DELETE  {{baseUrl}}/user/starred/titisriz/notesapp
Accept: {{accepHeader}}
Authorization : bearer {{token}}
Content-Length: 0

###

GET  {{baseUrl}}/user/starred/titisriz/notesapp
Accept: {{accepHeader}}
Authorization : bearer {{token}}
Content-Length: 0
